[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000013320988A50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/9c271d810e3ead889e6c285ddceb15d5
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000013320989450>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/9c271d810e3ead889e6c285ddceb15d5
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000013320911E00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/9c271d810e3ead889e6c285ddceb15d5