[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000013320D26140>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/7f0c1134400d984a961d6f82f132e003
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000013320D26580>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/7f0c1134400d984a961d6f82f132e003
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000013320D268B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/7f0c1134400d984a961d6f82f132e003